name: CI Pipeline Clima


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout de código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Build Docker Image
        run: |
          docker build -t mi-app-clima:${{ github.sha }} .
          docker tag mi-app-clima:${{ github.sha }} mi-app-clima:latest

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'mi-app-clima:latest'
          format: 'table'
          exit-code: '1' 
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Pipeline completo
        run: echo "La imagen ha sido construida y escaneada con éxito."

        # 5. Iniciar sesión en Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ddelacortep/weather-app:latest
      
      # 7. Despliegue en AWS
      - name: Deploy to AWS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            # 1. Parar el contenedor actual
            sudo docker stop weather-app || true
            
            # 2. Eliminar el contenedor
            sudo docker rm weather-app || true
            
            # 3. Eliminar la imagen vieja para no dejar rastro
            sudo docker rmi ddelacortep/weather-app:latest || true
            
            # 4. Hacer el pull de la nueva imagen desde Docker Hub
            sudo docker pull ddelacortep/weather-app:latest
            
            # 5. Crear y ejecutar el nuevo contenedor
            sudo docker run -d \
              --name weather-app \
              -p 80:8000 \
              --restart always \
              -e API_KEY="${{ secrets.API_KEY }}" \
              ddelacortep/weather-app:latest